openapi: 3.0.3
info:
  title: Delivery Service API
  version: "1.0.0"
  description: A RESTful API for managing deliveries and pricing requests.

tags:
  - name: PricingRequests
  - name: Deliveries

paths:
  /deliveries/pricing-requests:
    post:
      tags:
        - PricingRequests
      summary: Create a new pricing request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PricingRequestInput"
      responses:
        "201":
          description: Pricing request created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingRequest"

  /deliveries/pricing-requests/{pricingRequestId}:
    get:
      tags:
        - PricingRequests
      summary: Retrieve a specific pricing request
      parameters:
        - in: path
          name: pricingRequestId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Pricing request found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingRequestOutput"
        "404":
          description: Pricing request not found

  /deliveries:
    post:
      tags:
        - Deliveries
      summary: Create a new delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeliveryInput"
      responses:
        "201":
          description: Delivery created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Delivery"

  /deliveries/{deliveryId}:
    get:
      tags:
        - Deliveries
      summary: Retrieve a specific delivery
      parameters:
        - in: path
          name: deliveryId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Delivery found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Delivery"
        "404":
          description: Delivery not found
    # put:
    #   tags:
    #     - Deliveries
    #   summary: Update a delivery
    #   parameters:
    #     - in: path
    #       name: deliveryId
    #       required: true
    #       schema:
    #         type: string
    #         format: uuid
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: "#/components/schemas/DeliveryInput"
    #   responses:
    #     "200":
    #       description: Delivery updated successfully
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/Delivery"
    #     "404":
    #       description: Delivery not found

    # delete:
    #   tags:
    #     - Deliveries
    #   summary: Delete a delivery
    #   parameters:
    #     - in: path
    #       name: deliveryId
    #       required: true
    #       schema:
    #         type: string
    #         format: uuid
    #   responses:
    #     "204":
    #       description: Delivery deleted successfully
    #     "404":
    #       description: Delivery not found

  /deliveries/{id}/driver-decision:
    post:
      tags:
        - Deliveries
      summary: Selected driver chooses to accept or reject a delivery
      operationId: choiceDriver
      description: allows the selected driver to accept or reject a delivery request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deliveryId:
                  type: string
                driverId:
                  type: string
                choice:
                  type: string
                  enum:
                    - ACCEPTED
                    - REJECTED
            example:
              deliveryId: "123"
              driverId: "456"
              choice: ACCEPTED
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
              example:
                status: success
                data: ""

  /deliveries/{id}/driver-cancel:
    post:
      tags:
        - Deliveries
      summary: Cancel a delivery
      operationId: cancelDelivery
      description: allows the selected driver to cancel the delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deliveryRequestId:
                  type: string
                driverId:
                  type: string
                reason:
                  type: string
                  enum:
                    - VEHICLE_ISSUE
                    -
            example:
              deliveryId: "123"
              driverId: "456"
              reason: VEHICLE_ISSUE
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: string
              example:
                status: success
                data: ""

components:
  schemas:
    PricingRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        recommendedCategory:
          type: string
          enum: [BASE, XL]

        # pickupAddress:
        #   type: object
        #   properties:
        #     lat:
        #       type: number
        #       format: float
        #     lng:
        #       type: number
        #       format: float
        #     street:
        #       type: string
        #     city:
        #       type: string
        #     state:
        #       type: string
        #     postalCode:
        #       type: string
        #     country:
        #       type: string
        #   required:
        #     - lat
        #     - lng
        #     - street
        #     - city
        #     - state
        #     - postalCode
        #     - country
        # dropoffAddress:
        #   type: object
        #   properties:
        #     lat:
        #       type: number
        #       format: float
        #     lng:
        #       type: number
        #       format: float
        #     street:
        #       type: string
        #     city:
        #       type: string
        #     state:
        #       type: string
        #     postalCode:
        #       type: string
        #     country:
        #       type: string
        #   required:
        #     - lat
        #     - lng
        #     - street
        #     - city
        #     - state
        #     - postalCode
        #     - country

        totalFee:
          type: number
          format: float
        surcharges:
          type: array
          items:
            type: object
            properties:
              reason:
                type: string
              fee:
                type: number
                format: float
        distanceCharge:
          type: number
          format: float
        weightCharge:
          type: number
          format: float
        travelDistance:
          type: integer
        travelTime:
          type: integer
        selectedPickupTime:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - recommendedCategory
        - totalFee

    PricingRequestOutput:
      type: object
      properties:
        category:
          type: string
          enum: [BASE, XL]
        weightCharges:
          type: number
          format: float
        distanceCharges:
          type: number
          format: float
        pickupTime:
          type: string
          format: date-time
        surcharges:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              amount:
                type: number
                format: float
        estimatedTravelTime:
          type: string
          format: date-time
        total:
          type: number
          format: float
    PricingRequestInput:
      type: object
      properties:
        pickupAddress:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            country:
              type: string
          required:
            - street
            - city
            - state
            - postalCode
            - country
        dropoffAddress:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            country:
              type: string
          required:
            - street
            - city
            - state
            - postalCode
            - country
        items:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              baseWeight:
                type: integer
              height:
                type: number
                format: float
              width:
                type: number
                format: float
              length:
                type: number
                format: float
            required:
              - title
              - baseWeight
        selectedPickupTime:
          type: string

    Delivery:
      type: object
      properties:
        id:
          type: string
          format: uuid
        driverId:
          type: string
          format: uuid
        orderId:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - AWAITING_PICKUP
            - IN_TRANSIT
            - DELIVERED
            - ORDER_CANCELLED
            - DRIVER_CANCELLED
        cancellationReason:
          type: string
        cancelledAt:
          type: string
          format: date-time
        category:
          type: string
          enum: [BASE, XL]
        deliveryNotes:
          type: string
        pickupTime:
          type: string
        travelDistance:
          type: integer
        travelTime:
          type: integer
        eta:
          type: integer
        # pickupAddressFull:
        #   type: string
        dropoffAddressFull:
          type: string
        oversizedAssistanceRequired:
          type: boolean
        pickupLat:
          type: number
          format: float
          description: only shown to driver requests
        pickupLng:
          type: number
          format: float
          description: only shown to driver requests

        dropoffLat:
          type: number
          format: float
        dropoffLng:
          type: number
          format: float
        fee:
          type: number
          format: float
        startedAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - status
        - createdAt
        - updatedAt

    DeliveryInput:
      type: object
      properties:
        driverId:
          type: string
          format: uuid
        orderId:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - AWAITING_PICKUP
            - IN_TRANSIT
            - DELIVERED
            - ORDER_CANCELLED
            - DRIVER_CANCELLED
        cancellationReason:
          type: string
        cancelledAt:
          type: string
          format: date-time
        category:
          type: string
          enum: [BASE, XL]
        deliveryNotes:
          type: string
        pickupTime:
          type: string
        travelDistance:
          type: integer
        travelTime:
          type: integer
        eta:
          type: integer
        pickupAddressFull:
          type: string
        dropoffAddressFull:
          type: string
        oversizedAssistanceRequired:
          type: boolean
        pickupLat:
          type: number
          format: float
        pickupLng:
          type: number
          format: float
        dropoffLat:
          type: number
          format: float
        dropoffLng:
          type: number
          format: float
        fee:
          type: number
          format: float
        startedAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
