openapi: 3.0.3
info:
  title: Delivery Service API
  version: "1.0.0"
  description: A RESTful API for managing pricing requests and deliveries.

tags:
  - name: PricingRequests
    description: Operations related to pricing requests
  - name: Deliveries
    description: Retrieval and driver actions on deliveries

paths:
  /deliveries/pricing-requests:
    post:
      tags:
        - PricingRequests
      summary: Create a new pricing request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PricingRequestInput"
      responses:
        "201":
          description: Pricing request created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingRequestOutput"

  /deliveries/pricing-requests/{pricingRequestId}:
    get:
      tags:
        - PricingRequests
      summary: Retrieve a specific pricing request
      parameters:
        - name: pricingRequestId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Pricing request found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingRequestOutput"
        "404":
          description: Pricing request not found

  /deliveries/{deliveryId}:
    get:
      tags:
        - Deliveries
      summary: Retrieve a specific delivery
      parameters:
        - name: deliveryId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Delivery found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeliveryOutput"
        "404":
          description: Delivery not found

  /deliveries/{deliveryId}/cancel:
    post:
      tags:
        - Deliveries
      summary: Driver cancels a delivery
      operationId: cancelDelivery
      parameters:
        - name: deliveryId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CancelInput"
      responses:
        "200":
          description: Cancellation recorded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseOutput"

  /delivery-requests/{id}/decision:
    post:
      tags:
        - Deliveries
      summary: Driver accepts or rejects a delivery request
      operationId: deliveryRequestDecision
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DecisionInput"
      responses:
        "200":
          description: Decision recorded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseOutput"

components:
  schemas:
    # Pricing Requests
    PricingRequestInput:
      type: object
      required:
        - pickupAddress
        - deliveryAddress
        - items
      properties:
        pickupAddress:
          type: string
        deliveryAddress:
          type: string
        selectedPickupTime:
          type: string
          format: date-time
        items:
          type: array
          items:
            type: object
            required:
              - title
              - baseWeight
            properties:
              title:
                type: string
              baseWeight:
                type: integer
              height:
                type: number
                format: float
              width:
                type: number
                format: float
              length:
                type: number
                format: float

    PricingRequestOutput:
      type: object
      required:
        - id
        - recommendedCategory
        - totalFee
      properties:
        id:
          type: string
          format: uuid
        recommendedCategory:
          type: string
          enum:
            - BASE
            - XL
        totalFee:
          type: number
          format: float
        surcharges:
          type: array
          items:
            type: object
            properties:
              reason:
                type: string
              fee:
                type: number
                format: float
        distanceCharge:
          type: number
          format: float
        weightCharge:
          type: number
          format: float
        travelDistance:
          type: integer
        travelDistanceText:
          type: string
        travelTime:
          type: integer
        travelTimeText:
          type: string
        selectedPickupTime:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    # Delivery Retrieval
    DeliveryOutput:
      type: object
      required:
        - id
        - status
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        driverId:
          type: string
          format: uuid
        orderId:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - AWAITING_PICKUP
            - IN_TRANSIT
            - DELIVERED
            - ORDER_CANCELLED
            - DRIVER_CANCELLED
        cancellationReason:
          type: string
        cancelledAt:
          type: string
          format: date-time
        category:
          type: string
          enum:
            - BASE
            - XL
        deliveryNotes:
          type: string
        pickupTime:
          type: string
          format: date-time
        travelDistance:
          type: integer
        travelTime:
          type: integer
        eta:
          type: integer
        deliveryAddressFull:
          type: string
        oversizedAssistanceRequired:
          type: boolean
        pickupLat:
          type: number
          format: float
        pickupLng:
          type: number
          format: float
        deliveryLat:
          type: number
          format: float
        deliveryLng:
          type: number
          format: float
        fee:
          type: number
          format: float
        startedAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    # Driver Actions
    DecisionInput:
      type: object
      required:
        - driverId
        - choice
      properties:
        deliveryId:
          type: string
          format: uuid
        driverId:
          type: string
          format: uuid
        choice:
          type: string
          enum:
            - ACCEPTED
            - REJECTED

    CancelInput:
      type: object
      required:
        - driverId
        - reason
      properties:
        deliveryId:
          type: string
          format: uuid
        driverId:
          type: string
          format: uuid
        reason:
          type: string
          enum:
            - VEHICLE_ISSUE
            - OTHER

    ApiResponseOutput:
      type: object
      properties:
        status:
          type: string
        data:
          type: string
