AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  anar-server

Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON

Resources:
  ListingService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/listing-service/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      # Add environment variables here
      Environment:
        Variables:
          DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      Events:
        LS_PostListing:
          Type: Api
          Properties:
            Path: /listings
            Method: post

        LS_GetListings:
          Type: Api
          Properties:
            Path: /listings
            Method: get

        LS_GetListingById:
          Type: Api
          Properties:
            Path: /listings/{id}
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  PaymentService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/payment-service/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      # Add environment variables here
      Environment:
        Variables:
          DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      Events:
        PS_PaymentIntent:
          Type: Api
          Properties:
            Path: /start-payment-intent
            Method: post

        PS_Cors:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options

        PS_Webhook:
          Type: Api
          Properties:
            Path: /payment-service/webhook
            Method: post

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  DeliveryService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/delivery-service/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      # Add environment variables here
      Environment:
        Variables:
          DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      Events:
        DS_CreatePricingRequest:
          Type: Api
          Properties:
            Path: /pricing-requests
            Method: post

        DS_Cors:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  OrderService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/order-service/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      # Add environment variables here
      Environment:
        Variables:
          DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      Events:
        OS_GetCheckout:
          Type: Api
          Properties:
            Path: /checkout
            Method: get

        OS_Cors:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
