openapi: 3.0.3
info:
  title: Order Service API
  version: "1.0.0"
  description: A RESTful API for managing checkouts and orders in the order service.
servers:
  - url: http://order.example.com/v1
tags:
  - name: Checkout-Session
  - name: Orders

paths:
  /checkout-session-init:
    post:
      tags:
        - Checkout-Session
      summary: Create a new checkout-session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listingIds:
                  type: array
                  items:
                    type: string
                    format: uuid
      responses:
        "201":
          description: Checkout-session created successfully and id is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkoutSessionId:
                    type: string
                    format: uuid

  /checkout-session/{checkoutSessionId}/summary:
    post:
      tags:
        - Checkout-Session
      summary: Retrieve a summary of the checkout-session
      parameters:
        - in: path
          name: checkoutSessionId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: A summary of the checkout-session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutSession"

  /orders:
    get:
      tags:
        - Orders
      summary: Retrieve all orders
      responses:
        "200":
          description: A list of order records.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      tags:
        - Orders
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderInput"
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Retrieve a specific order
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Order found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
    put:
      tags:
        - Orders
      summary: Update an existing order
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderInput"
      responses:
        "200":
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
    delete:
      tags:
        - Orders
      summary: Delete an order
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
            format: uuid

      responses:
        "204":
          description: Order deleted successfully
        "404":
          description: Order not found

components:
  schemas:
    CheckoutSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
        listingIds:
          type: array
          items:
            type: string
            format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        orderNotes:
          type: string
        deliveryAddress:
          type: string
        deliveryDetails:
          type: object
          properties:
            category:
              type: string
              enum: [BASE, XL]
            weightCharges:
              type: number
              format: float
            distanceCharges:
              type: number
              format: float
            pickupTime:
              type: string
              format: date-time
            surcharges:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  amount:
                    type: number
                    format: float
            estimatedTravelTime:
              type: string
              format: date-time
            total:
              type: number
              format: float
        subtotal:
          type: number
          format: float
      required:
        - id
        - listingIds
        - status
        - createdAt
        - updatedAt

    CheckoutSessionInput:
      type: object
      properties:
        orderNotes:
          type: string
        deliveryAddress:
          type: string
        pickupTime:
          type: string
      required:
        - listingIds
        - status

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        listingIds:
          type: array
          items:
            type: string
            format: uuid
        customerInfo:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            phone:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [PENDING, COMPLETED]
        orderNotes:
          type: string
        deliveryAddress:
          type: string
        deliveryPricingRequestId:
          type: string
          format: uuid
      required:
        - id
        - listingIds
        - status
        - createdAt
        - updatedAt

    OrderInput:
      type: object
      properties:
        listingIds:
          type: array
          items:
            type: string
            format: uuid
        customerInfo:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            phone:
              type: string
        status:
          type: string
          enum: [PENDING, COMPLETED]
        orderNotes:
          type: string
        deliveryAddress:
          type: string
        deliveryPricingRequestId:
          type: string
          format: uuid
      required:
        - listingIds
        - status
