openapi: 3.0.3
info:
  title: Listing Service API
  version: "1.0.0"
  description: A RESTful API for managing product listings in the listing service.
servers:
  - url: https://api.example.com/v1
    description: Production server (replace with your actual server)
tags:
  - name: Listings
    description: Operations related to product listings

paths:
  /listings:
    get:
      tags:
        - Listings
      summary: Retrieve all listings
      description: Retrieve a list of all available product listings.
      responses:
        "200":
          description: A JSON array of product listing objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Listing"
              example:
                - id: "123e4567-e89b-12d3-a456-426614174010"
                  title: "Wireless Bluetooth Headphones"
                  type: "SALE"
                  sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
                  price: 199.99
                  description: "High quality wireless Bluetooth headphones with noise cancellation."
                  photo_urls:
                    - "https://example.com/photos/headphones1.jpg"
                  condition: "NEW"
                  specs:
                    color: "Black"
                    material: "Plastic"
                    size: "Standard"
                  availableQty: 50
                  category: "Electronics"
                  subCategory: "Audio"
                  priceNegotiable: false
                  isFragile: false
        "500":
          description: Server error.
    post:
      tags:
        - Listings
      summary: Create a new listing
      description: Create a new product listing with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingInput"
            example:
              title: "Wireless Bluetooth Headphones"
              type: "SALE"
              sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
              price: 199.99
              description: "High quality wireless Bluetooth headphones with noise cancellation."
              photo_urls:
                - "https://example.com/photos/headphones1.jpg"
              condition: "NEW"
              specs:
                color: "Black"
                material: "Plastic"
                size: "Standard"
              availableQty: 50
              category: "Electronics"
              subCategory: "Audio"
              priceNegotiable: false
              isFragile: false
      responses:
        "201":
          description: Listing created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174010"
                title: "Wireless Bluetooth Headphones"
                type: "SALE"
                sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
                price: 199.99
                description: "High quality wireless Bluetooth headphones with noise cancellation."
                photo_urls:
                  - "https://example.com/photos/headphones1.jpg"
                condition: "NEW"
                specs:
                  color: "Black"
                  material: "Plastic"
                  size: "Standard"
                availableQty: 50
                category: "Electronics"
                subCategory: "Audio"
                priceNegotiable: false
                isFragile: false
        "400":
          description: Invalid input data.

  /listings/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The unique identifier of the product listing.
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Listings
      summary: Retrieve a specific listing
      description: Retrieve details of a product listing by its unique ID.
      responses:
        "200":
          description: Listing details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174010"
                title: "Wireless Bluetooth Headphones"
                type: "SALE"
                sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
                price: 199.99
                description: "High quality wireless Bluetooth headphones with noise cancellation."
                photo_urls:
                  - "https://example.com/photos/headphones1.jpg"
                condition: "NEW"
                specs:
                  color: "Black"
                  material: "Plastic"
                  size: "Standard"
                availableQty: 50
                category: "Electronics"
                subCategory: "Audio"
                priceNegotiable: false
                isFragile: false
        "404":
          description: Listing not found.
    put:
      tags:
        - Listings
      summary: Update a listing
      description: Update the details of an existing product listing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingInput"
            example:
              title: "Wireless Bluetooth Headphones - Discounted"
              type: "SALE"
              sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
              price: 179.99
              description: "Discounted price on high quality wireless Bluetooth headphones with noise cancellation."
              photo_urls:
                - "https://example.com/photos/headphones1_discount.jpg"
              condition: "NEW"
              specs:
                color: "Black"
                material: "Plastic"
                size: "Standard"
              availableQty: 45
              category: "Electronics"
              subCategory: "Audio"
              priceNegotiable: false
              isFragile: false
      responses:
        "200":
          description: Listing updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174010"
                title: "Wireless Bluetooth Headphones - Discounted"
                type: "SALE"
                sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
                price: 179.99
                description: "Discounted price on high quality wireless Bluetooth headphones with noise cancellation."
                photo_urls:
                  - "https://example.com/photos/headphones1_discount.jpg"
                condition: "NEW"
                specs:
                  color: "Black"
                  material: "Plastic"
                  size: "Standard"
                availableQty: 45
                category: "Electronics"
                subCategory: "Audio"
                priceNegotiable: false
                isFragile: false
        "400":
          description: Invalid input data.
        "404":
          description: Listing not found.
    delete:
      tags:
        - Listings
      summary: Delete a listing
      description: Delete a product listing by its unique ID.
      responses:
        "204":
          description: Listing deleted successfully.
        "404":
          description: Listing not found.

components:
  schemas:
    Listing:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the product listing.
        title:
          type: string
          description: Title or name of the product listing.
        type:
          type: string
          enum:
            - SALE
            - RENT
          description: The type of listing (SALE or RENT).
        sellerId:
          type: string
          description: Foreign key reference to the seller.
        price:
          type: number
          format: float
          description: Price of the product.
        description:
          type: string
          description: Detailed description of the product listing.
        photo_urls:
          type: array
          items:
            type: string
          description: Array of photo URLs for the product.
        condition:
          type: string
          enum:
            - NEW
            - GREAT
            - GOOD
            - FAIR
          description: Condition of the product.
        specs:
          $ref: "#/components/schemas/ListingMetadata"
          description: Specifications or metadata for the product.
        availableQty:
          type: integer
          description: Quantity available.
        category:
          type: string
          description: Main category under which the product is classified.
        subCategory:
          type: string
          description: More specific classification within the category.
        priceNegotiable:
          type: boolean
          description: Indicates whether the price is negotiable.
        isFragile:
          type: boolean
          description: Indicates whether the product is fragile.
      required:
        - id
        - title
        - type
        - sellerId
        - price
      example:
        id: "123e4567-e89b-12d3-a456-426614174010"
        title: "Wireless Bluetooth Headphones"
        type: "SALE"
        sellerId: "seller_4d4063f5-b78c-4501-a325-1179b44d826f"
        price: 199.99
        description: "High quality wireless Bluetooth headphones with noise cancellation."
        photo_urls:
          - "https://example.com/photos/headphones1.jpg"
        condition: "NEW"
        specs:
          color: "Black"
          material: "Plastic"
          size: "Standard"
        availableQty: 50
        category: "Electronics"
        subCategory: "Audio"
        priceNegotiable: false
        isFragile: false

    ListingMetadata:
      type: object
      properties:
        color:
          type: string
          description: Color of the product.
        material:
          type: string
          description: Material of the product.
        size:
          type: string
          description: Size or dimensions of the product.
      required:
        - color
        - material
        - size
      example:
        color: "Black"
        material: "Plastic"
        size: "Standard"

    ListingInput:
      type: object
      properties:
        title:
          type: string
          description: Title or name of the product listing.
        type:
          type: string
          enum:
            - SALE
            - RENT
          description: The type of listing (SALE or RENT).
          default: SALE
        sellerId:
          type: string
          description: Foreign key reference to the seller.
        price:
          type: number
          format: float
          description: Price of the product.
        description:
          type: string
          description: Detailed description of the product listing.
        photo_urls:
          type: array
          items:
            type: string
          description: Array of photo URLs for the product.
        condition:
          type: string
          enum:
            - NEW
            - GREAT
            - GOOD
            - FAIR
          description: Condition of the product.
        specs:
          $ref: "#/components/schemas/ListingMetadata"
          description: Specifications or metadata for the product.
        availableQty:
          type: integer
          description: Quantity available.
        category:
          type: string
          description: Main category under which the product is classified.
        subCategory:
          type: string
          description: More specific classification within the category.
        priceNegotiable:
          type: boolean
          description: Indicates whether the price is negotiable.
          default: false
        isFragile:
          type: boolean
          description: Indicates whether the product is fragile.
          default: false
      required:
        - title
        - type
        - sellerId
        - price
        - category
        - subCategory
        - photo_urls
        - description
        - condition
        - availableQty
      example:
        title: "Wireless Bluetooth Headphones"
        type: "SALE"
        sellerId: "seller_002"
        price: 199.99
        description: "High quality wireless Bluetooth headphones with noise cancellation."
        photo_urls:
          - "https://example.com/photos/headphones1.jpg"
        condition: "NEW"
        specs:
          color: "Black"
          material: "Plastic"
          size: "Standard"
        availableQty: 50
        category: "Electronics"
        subCategory: "Audio"
        priceNegotiable: false
        isFragile: false
