openapi: 3.0.3
info:
  title: Listing Service API
  version: "1.0.0"
  description: A RESTful API for managing listings in the listing service.
servers:
  - url: https://api.example.com/v1
    description: Production server (replace with your actual server)
tags:
  - name: Listings
    description: Operations related to listings

paths:
  /listings:
    get:
      tags:
        - Listings
      summary: Retrieve all listings
      description: Retrieve a list of all available listings.
      responses:
        "200":
          description: A JSON array of listing objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Listing"
              example:
                - id: "123e4567-e89b-12d3-a456-426614174001"
                  title: "Charming Family Home for Sale"
                  type: "SALE"
                  sellerId: "seller_002"
                  price: 350000.00
                  description: "A beautifully maintained home in a quiet suburban neighborhood."
                  photo_urls:
                    - "https://example.com/photos/house1.jpg"
                  condition: "GOOD"
                  specs:
                    color: "Blue"
                    material: "Brick"
                    size: "2500 sqft"
                  availableQty: 1
                  category: "Real Estate"
                  subCategory: "House"
                  priceNegotiable: false
                  isFragile: false
        "500":
          description: Server error.
    post:
      tags:
        - Listings
      summary: Create a new listing
      description: Create a new listing with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingInput"
            example:
              title: "Charming Family Home for Sale"
              type: "SALE"
              sellerId: "seller_002"
              price: 350000.00
              description: "A beautifully maintained home in a quiet suburban neighborhood."
              photo_urls:
                - "https://example.com/photos/house1.jpg"
              condition: "GOOD"
              specs:
                color: "Blue"
                material: "Brick"
                size: "2500 sqft"
              availableQty: 1
              category: "Real Estate"
              subCategory: "House"
              priceNegotiable: false
              isFragile: false
      responses:
        "201":
          description: Listing created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174001"
                title: "Charming Family Home for Sale"
                type: "SALE"
                sellerId: "seller_002"
                price: 350000.00
                description: "A beautifully maintained home in a quiet suburban neighborhood."
                photo_urls:
                  - "https://example.com/photos/house1.jpg"
                condition: "GOOD"
                specs:
                  color: "Blue"
                  material: "Brick"
                  size: "2500 sqft"
                availableQty: 1
                category: "Real Estate"
                subCategory: "House"
                priceNegotiable: false
                isFragile: false
        "400":
          description: Invalid input data.

  /listings/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The unique identifier of the listing.
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Listings
      summary: Retrieve a specific listing
      description: Retrieve details of a listing by its unique ID.
      responses:
        "200":
          description: Listing details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174001"
                title: "Charming Family Home for Sale"
                type: "SALE"
                sellerId: "seller_002"
                price: 350000.00
                description: "A beautifully maintained home in a quiet suburban neighborhood."
                photo_urls:
                  - "https://example.com/photos/house1.jpg"
                condition: "GOOD"
                specs:
                  color: "Blue"
                  material: "Brick"
                  size: "2500 sqft"
                availableQty: 1
                category: "Real Estate"
                subCategory: "House"
                priceNegotiable: false
                isFragile: false
        "404":
          description: Listing not found.
    put:
      tags:
        - Listings
      summary: Update a listing
      description: Update the details of an existing listing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListingInput"
            example:
              title: "Charming Family Home for Sale - Price Reduced"
              type: "SALE"
              sellerId: "seller_002"
              price: 345000.00
              description: "Updated price for a beautifully maintained home in a quiet suburban neighborhood."
              photo_urls:
                - "https://example.com/photos/house1_updated.jpg"
              condition: "GOOD"
              specs:
                color: "Blue"
                material: "Brick"
                size: "2500 sqft"
              availableQty: 1
              category: "Real Estate"
              subCategory: "House"
              priceNegotiable: false
              isFragile: false
      responses:
        "200":
          description: Listing updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Listing"
              example:
                id: "123e4567-e89b-12d3-a456-426614174001"
                title: "Charming Family Home for Sale - Price Reduced"
                type: "SALE"
                sellerId: "seller_002"
                price: 345000.00
                description: "Updated price for a beautifully maintained home in a quiet suburban neighborhood."
                photo_urls:
                  - "https://example.com/photos/house1_updated.jpg"
                condition: "GOOD"
                specs:
                  color: "Blue"
                  material: "Brick"
                  size: "2500 sqft"
                availableQty: 1
                category: "Real Estate"
                subCategory: "House"
                priceNegotiable: false
                isFragile: false
        "400":
          description: Invalid input data.
        "404":
          description: Listing not found.
    delete:
      tags:
        - Listings
      summary: Delete a listing
      description: Delete a listing by its unique ID.
      responses:
        "204":
          description: Listing deleted successfully.
        "404":
          description: Listing not found.

components:
  schemas:
    Listing:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the listing.
        title:
          type: string
          description: Title or name of the listing.
        type:
          type: string
          enum:
            - SALE
            - RENT
          description: The type of listing (SALE or RENT).
        sellerId:
          type: string
          description: Foreign key reference to the seller.
        price:
          type: number
          format: float
          description: Price of the item or service.
        description:
          type: string
          description: Detailed description of the listing.
        photo_urls:
          type: array
          items:
            type: string
          description: Array of photo URLs for the listing.
        condition:
          type: string
          enum:
            - NEW
            - GREAT
            - GOOD
            - FAIR
          description: Condition of the item.
        specs:
          $ref: "#/components/schemas/ListingMetadata"
          description: Specifications or metadata for the listing.
        availableQty:
          type: integer
          description: Quantity available.
        category:
          type: string
          description: Main category under which the listing is classified.
        subCategory:
          type: string
          description: More specific classification within the category.
        priceNegotiable:
          type: boolean
          description: Indicates whether the price is negotiable.
        isFragile:
          type: boolean
          description: Indicates whether the item is fragile.
      required:
        - id
        - title
        - type
        - sellerId
        - price
      example:
        id: "123e4567-e89b-12d3-a456-426614174001"
        title: "Charming Family Home for Sale"
        type: "SALE"
        sellerId: "seller_002"
        price: 350000.00
        description: "A beautifully maintained home in a quiet suburban neighborhood."
        photo_urls:
          - "https://example.com/photos/house1.jpg"
        condition: "GOOD"
        specs:
          color: "Blue"
          material: "Brick"
          size: "2500 sqft"
        availableQty: 1
        category: "Real Estate"
        subCategory: "House"
        priceNegotiable: false
        isFragile: false

    ListingMetadata:
      type: object
      properties:
        color:
          type: string
          description: Color of the item.
        material:
          type: string
          description: Material of the item.
        size:
          type: string
          description: Size or dimensions of the item.
      required:
        - color
        - material
        - size
      example:
        color: "Blue"
        material: "Brick"
        size: "2500 sqft"

    ListingInput:
      type: object
      properties:
        title:
          type: string
          description: Title or name of the listing.
        type:
          type: string
          enum:
            - SALE
            - RENT
          description: The type of listing (SALE or RENT).
          default: SALE
        sellerId:
          type: string
          description: Foreign key reference to the seller.
        price:
          type: number
          format: float
          description: Price of the item or service.
        description:
          type: string
          description: Detailed description of the listing.
        photo_urls:
          type: array
          items:
            type: string
          description: Array of photo URLs for the listing.
        condition:
          type: string
          enum:
            - NEW
            - GREAT
            - GOOD
            - FAIR
          description: Condition of the item.
        specs:
          $ref: "#/components/schemas/ListingMetadata"
          description: Specifications or metadata for the listing.
        availableQty:
          type: integer
          description: Quantity available.
        category:
          type: string
          description: Main category under which the listing is classified.
        subCategory:
          type: string
          description: More specific classification within the category.
        priceNegotiable:
          type: boolean
          description: Indicates whether the price is negotiable.
          default: false
        isFragile:
          type: boolean
          description: Indicates whether the item is fragile.
          default: false
      required:
        - title
        - type
        - sellerId
        - price
        - category
        - subCategory
        - photo_urls
        - description
        - condition
        - availableQty
      example:
        title: "Charming Family Home for Sale"
        type: "SALE"
        sellerId: "seller_002"
        price: 350000.00
        description: "A beautifully maintained home in a quiet suburban neighborhood."
        photo_urls:
          - "https://example.com/photos/house1.jpg"
        condition: "GOOD"
        specs:
          color: "Blue"
          material: "Brick"
          size: "2500 sqft"
        availableQty: 1
        category: "Real Estate"
        subCategory: "House"
        priceNegotiable: false
        isFragile: false
