name: Deploy Serverless on PR to dev

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci


      - name: Database Migration
        run: npx drizzle-kit migrate --config=drizzle.dev.config.ts

      - name: Deploy Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: npx serverless deploy --stage dev --region us-west-2
